spring:
  datasource:
    url:  jdbc:mysql://localhost/auth
    username: root
    password:
    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
server:
  port: 8090